baseURL = "https://compositionalit.github.io/farmer/"
languageCode = "en-gb"
title = "Farmer"
author = "Compositional IT"
theme = "hugo-theme-learn"
[outputs]
relativeUrls = true
home = [ "HTML", "RSS", "JSON"]
[params]
    themeVariant="green"
    editURL = "https://github.com/CompositionalIT/farmer/tree/master/docs/content/"
    description = "Farmer - Making repeatable Azure deployments easy!"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/compositionalit/farmer"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-microsoft'></i> Nuget"
identifier = "nuget"
url = "https://www.nuget.org/packages/Farmer/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<img src='/farmer/images/cit.png'></img> Compositional IT"
identifier = "cit"
url = "https://compositional-it.com"
weight = 11
